version: '2'
services:
    mysql:
        container_name: mysql
        image: mysql:5.7.13
        volumes:
            - ~/volumes/mysql_5.7.13/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=mydatabase
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
